// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyOsz0Rr8nASBaTz36WOmBJQybAu_P-FY',
    appId: '1:714792558226:web:c32719708858f5bea0104b',
    messagingSenderId: '714792558226',
    projectId: 'next-hire-62f3f',
    authDomain: 'next-hire-62f3f.firebaseapp.com',
    storageBucket: 'next-hire-62f3f.firebasestorage.app',
    measurementId: 'G-13PXVGWBNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK_lJD7zgUI_GN_19Onn8QPD_2EtEnIeU',
    appId: '1:714792558226:android:95d4b4ea06eeae36a0104b',
    messagingSenderId: '714792558226',
    projectId: 'next-hire-62f3f',
    storageBucket: 'next-hire-62f3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhRCVZeZ--vx4nSNSL823moVBCg0vJO4o',
    appId: '1:714792558226:ios:449f0cb224e755c0a0104b',
    messagingSenderId: '714792558226',
    projectId: 'next-hire-62f3f',
    storageBucket: 'next-hire-62f3f.firebasestorage.app',
    iosBundleId: 'com.example.nextHire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhRCVZeZ--vx4nSNSL823moVBCg0vJO4o',
    appId: '1:714792558226:ios:449f0cb224e755c0a0104b',
    messagingSenderId: '714792558226',
    projectId: 'next-hire-62f3f',
    storageBucket: 'next-hire-62f3f.firebasestorage.app',
    iosBundleId: 'com.example.nextHire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyOsz0Rr8nASBaTz36WOmBJQybAu_P-FY',
    appId: '1:714792558226:web:0f9047f41295177fa0104b',
    messagingSenderId: '714792558226',
    projectId: 'next-hire-62f3f',
    authDomain: 'next-hire-62f3f.firebaseapp.com',
    storageBucket: 'next-hire-62f3f.firebasestorage.app',
    measurementId: 'G-MFTWBKGSRV',
  );
}
